"""Trading signal entities for algorithmic trading."""

from datetime import datetime
from decimal import Decimal
from enum import Enum

from pydantic import BaseModel, Field


class SignalType(str, Enum):
    """Types of trading signals."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    STRONG_BUY = "strong_buy"
    STRONG_SELL = "strong_sell"


class SignalConfidence(str, Enum):
    """Confidence levels for trading signals."""

    VERY_LOW = "very_low"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"


class TradingStrategy(str, Enum):
    """Trading strategy types."""

    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    BREAKOUT = "breakout"
    TREND_FOLLOWING = "trend_following"
    SCALPING = "scalping"
    SWING = "swing"
    ARBITRAGE = "arbitrage"
    AI_PREDICTIVE = "ai_predictive"


class TradingSignal(BaseModel):
    """Trading signal generated by analysis engine."""

    signal_id: str = Field(
        description="Unique identifier for the signal",
        examples=["sig_20240115_btc_001"],
        min_length=1,
    )
    symbol: str = Field(
        description="Trading symbol",
        examples=["BTC/USD"],
        min_length=1,
        max_length=20,
    )
    signal_type: SignalType = Field(
        description="Type of trading signal",
        examples=[SignalType.BUY],
    )
    confidence: SignalConfidence = Field(
        description="Confidence level of the signal",
        examples=[SignalConfidence.HIGH],
    )
    strategy: TradingStrategy = Field(
        description="Strategy that generated this signal",
        examples=[TradingStrategy.AI_PREDICTIVE],
    )
    entry_price: Decimal = Field(
        description="Suggested entry price",
        examples=[45123.50],
        gt=0,
    )
    target_price: Decimal | None = Field(
        default=None,
        description="Target price for profit taking",
        examples=[47000.00],
        gt=0,
    )
    stop_loss: Decimal | None = Field(
        default=None,
        description="Stop loss price for risk management",
        examples=[44000.00],
        gt=0,
    )
    expected_return: Decimal = Field(
        description="Expected return percentage",
        examples=[4.16],
    )
    risk_reward_ratio: Decimal = Field(
        description="Risk to reward ratio",
        examples=[2.5],
        gt=0,
    )
    time_horizon: str = Field(
        description="Expected duration of the trade",
        examples=["4h", "1d", "1w"],
        min_length=1,
    )
    ai_reasoning: str = Field(
        description="AI-generated explanation for the signal",
        examples=["Strong bullish momentum with RSI oversold and positive sentiment"],
        min_length=10,
    )
    supporting_indicators: dict[str, Decimal] = Field(
        description="Technical indicators supporting the signal",
        examples=[{"rsi": 32.5, "macd": 125.3, "volume_surge": 1.8}],
    )
    generated_at: datetime = Field(
        description="Timestamp when signal was generated",
        examples=["2024-01-15T10:30:00Z"],
    )
    expires_at: datetime | None = Field(
        default=None,
        description="Signal expiration timestamp",
        examples=["2024-01-15T14:30:00Z"],
    )
    is_active: bool = Field(
        default=True,
        description="Whether the signal is still active",
        examples=[True],
    )

    class Config:
        frozen = True
